-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estudiantes
(
    id serial NOT NULL,
    nombre character varying(200) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(200) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(200) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(200) COLLATE pg_catalog."default",
    correo character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT estudiantes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.materias
(
    id serial NOT NULL,
    codigo character varying(5) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(25) COLLATE pg_catalog."default" NOT NULL,
    "unidadCredito" character varying(5) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT materias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profesores
(
    id serial NOT NULL,
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    apellido character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cedula character varying(20) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    correo character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT profesores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial NOT NULL,
    "nombre completo" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(18) COLLATE pg_catalog."default" NOT NULL,
    password character varying(20) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.estudiantes
    ADD FOREIGN KEY (id)
    REFERENCES public.profesores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.materias
    ADD FOREIGN KEY (id)
    REFERENCES public.profesores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.materias
    ADD FOREIGN KEY (id)
    REFERENCES public.estudiantes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;