services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: gerardo
      POSTGRES_PASSWORD: desarrollo
    ports:
      - "5432:5432"


